#Postgresql Data Directory
PGDATA=/home/14pg/data
#Postgresql Archive Directory
ARCHIVE_DEST=/home/14pg/wal_arch
#the Disk that dropScan need to scan
DISK_PATH=
#The number of data blocks skipped during dropScan. The smaller the value, the more comprehensive the disk coverage, and the slower the speed.
BLOCK_INTERVAL=20
#PGDATA to be excluded during dropscan.
PGDATA_EXCLUDE=
